version: "3.9"
services:
  mysql:
    ports:
      - "3306:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "harcher"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData:
